# Generated by Django 5.0.3 on 2024-04-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(null=True, upload_to="blog/"),
        ),
    ]
